steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-python-app:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/my-python-app:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'my-python-app',
         '--image', 'gcr.io/$PROJECT_ID/my-python-app:$COMMIT_SHA',
         '--region', 'us-central1', # Replace with your preferred region
         '--platform', 'managed',
         '--allow-unauthenticated']
images:
- 'gcr.io/$PROJECT_ID/my-python-app:$COMMIT_SHA'
